### ISSUE TITLE
Redesign Paper wallet

### ISSUE THREAD

**Issue by chr1sn0** [pirl/MyPirlWallet#3]
- Update sidebar stub for paper wallet.
- Remove background icon.
- Set background to `#f0f0f0`

**Comment by MatWaller** [comment]
![sample](https://user-images.githubusercontent.com/8047888/31278261-380868a4-aa9c-11e7-8561-2353c0026bdc.png)


New wallet stub.

**Comment by chr1sn0** [comment]
bg icon removed

**Comment by chr1sn0** [comment]
background color set

**Comment by MatWaller** [comment]
Nice work @chr1sn0 

Works great think i will work on mobile styling when i free up some time but it's not urgent.
